FROM oven/bun:1.2-alpine AS base

RUN apk update && apk add --no-cache libc6-compat

WORKDIR /app
COPY package.json bun.lock* ./
RUN bun install

EXPOSE 3000
ENTRYPOINT [ "bun", "--bun", "run", "dev" ]
